use clap::CommandFactory;
use std::fs;
use std::path::Path;

#[path = "src/opts.rs"]
mod opts;

fn generate_man_page(
    cmd: clap::Command,
    out_path: &Path,
    extra_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let man = clap_mangen::Man::new(cmd);
    let mut buffer = Vec::new();
    man.render(&mut buffer)?;
    let mut man_str = String::from_utf8(buffer)?;

    // Set the section to 8 (default generated by clap is 1)
    let cmd_name = out_path.file_stem().unwrap().to_str().unwrap();
    man_str = man_str.replace(&format!(".TH {} 1", cmd_name), &format!(".TH {} 8", cmd_name));

    // Append extra sections if file exists
    if extra_path.exists() {
        let extra_content = fs::read_to_string(extra_path)?;
        man_str.push_str(&extra_content);
    }

    fs::write(out_path, man_str)?;
    Ok(())
}

fn main() {
    let out_dir = Path::new("man");
    if !out_dir.exists() {
        fs::create_dir_all(out_dir).expect("Failed to create man directory");
    }

    generate_man_page(
        opts::RsoftflowdArgs::command(),
        &out_dir.join("rsoftflowd.8"),
        &out_dir.join("rsoftflowd.extra.roff"),
    ).expect("Failed to generate rsoftflowd.8");

    generate_man_page(
        opts::RsoftflowctlArgs::command(),
        &out_dir.join("rsoftflowctl.8"),
        &out_dir.join("rsoftflowctl.extra.roff"),
    ).expect("Failed to generate rsoftflowctl.8");

    // Re-run build script if dependency files change
    println!("cargo:rerun-if-changed=src/opts.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=man/rsoftflowd.extra.roff");
    println!("cargo:rerun-if-changed=man/rsoftflowctl.extra.roff");
}
